//! Default deny for RM: only known controls and classes reach the host's RM.
//!
//! The backend is a client of the host's RM like any other user process, and
//! RM serves one GPU to every VM, every host process and the host desktop.
//! Before this gate every one of RM's ~1,370 exported controls and every
//! class it can make was one guest ioctl from the host kernel, with RM's own
//! privilege check the only filter. Now a control or class reaches RM only if
//! the host release's allowlist (`abi::rmallow`, generated by
//! `gen/rmallow_extract.py` from NVIDIA's sources and the hardware runs'
//! counts) has it: user-callable in RM's own tables, asked for by a
//! workload the project runs, and naming no host resource the backend does
//! not translate. Everything else is answered here, as RM answers what it
//! does not implement, and logged with RM's name for it (rate-limited by the
//! logger, per call site: `ratelimit.rs`), so bring-up can grow the list
//! from the log.
//!
//! Every v1 path into RM with a control or a class goes through [`RmAllow::
//! check`]: RM_CONTROL (and the control DEFERRED_API bundles), RM_ALLOC,
//! ALLOC_MEMORY, ALLOC_OBJECT, ALLOC_CONTEXT_DMA2 and VID_HEAP_CONTROL's
//! functions with the classes each allocates. IOCTL2 carries no RM call
//! (its schemas are DRM, NVKMS and UVM), and nothing else reaches RM with a
//! control or a class the guest chose.
//!
//! What it answers: a control RM would not recognise gets NV_ERR_NOT_SUPPORTED
//! (resControlLookup's answer), one sent with a parameter size other than
//! RM's gets NV_ERR_INVALID_PARAM_STRUCT (the same function's), a class
//! NV_ERR_INVALID_CLASS (serverAllocResourceUnderLock's for a class it has
//! no descriptor of), a VID_HEAP_CONTROL function NV_ERR_NOT_SUPPORTED: the
//! status in the block, the ioctl itself succeeding, as RM's are. Userspace
//! drivers probe with calls RM may not serve; they see what they would see
//! on a host whose RM lacks the call.
//!
//! `--rm-allowlist=log` keeps the log and forwards the call anyway, to find
//! what a new workload needs without breaking it; it is not a way to run
//! one. `--permissive-abi` does not touch this gate.

use abi::ioctl::*;
use abi::rmallow::{self, Release};
use abi::version::DriverVersion;

/// Whether the allowlist refuses, or only says what it would refuse.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub enum Mode {
    /// Refuse what the allowlist lacks (the default).
    #[default]
    Enforce,
    /// Log it and forward it anyway. Diagnostic only.
    Log,
}

impl std::str::FromStr for Mode {
    type Err = String;
    fn from_str(s: &str) -> Result<Self, String> {
        match s {
            "enforce" => Ok(Mode::Enforce),
            "log" => Ok(Mode::Log),
            other => Err(format!("{other:?}: expected `enforce` or `log`")),
        }
    }
}

/// NV_ERR_* (nvstatuscodes.h).
pub const NV_ERR_INVALID_CLASS: u32 = 0x22;
pub const NV_ERR_INVALID_PARAM_STRUCT: u32 = 0x3a;
pub const NV_ERR_NOT_SUPPORTED: u32 = 0x56;

/// NV5080_CTRL_CMD_DEFERRED_API and _V2: `{hApiHandle, cmd, ...}`, the
/// control RM runs later at `cmd`'s offset 4 of the parameters.
const DEFERRED_API: [u32; 2] = [0x5080_0101, 0x5080_0103];
const DEFERRED_CMD: usize = 4;

/// How a refused call is answered.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Refusal {
    /// RM's `status` at `at` of the top-level block, the ioctl succeeding.
    Status { at: usize, status: u32 },
    /// A block too short to hold what RM reads: the ioctl fails, as the
    /// host's would.
    Errno(i32),
}

/// What was refused, for the log and the teardown report.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum What {
    Control(u32),
    Class(u32),
    VidHeap(u32),
}

/// The gate. One per backend: the host's release, the mode, and counts of
/// what it refused.
#[derive(Debug)]
pub struct RmAllow {
    mode: Mode,
    release: &'static Release,
    /// Whether `release` was measured at the host's exact version: only
    /// then are parameter sizes held to it.
    exact: bool,
    refused_controls: crate::tally::Tally,
    refused_classes: crate::tally::Tally,
}

impl Default for RmAllow {
    fn default() -> Self {
        Self::new(Mode::default())
    }
}

fn rd32(b: &[u8], at: usize) -> Option<u32> {
    Some(u32::from_le_bytes(b.get(at..at + 4)?.try_into().ok()?))
}

impl RmAllow {
    /// Until the host's version is known, the newest release's list, sizes
    /// unchecked. The backend learns the version before a guest can call.
    pub fn new(mode: Mode) -> Self {
        Self {
            mode,
            release: rmallow::RELEASES.last().expect("at least one release"),
            exact: false,
            refused_controls: Default::default(),
            refused_classes: Default::default(),
        }
    }

    pub fn mode(&self) -> Mode {
        self.mode
    }

    pub fn set_mode(&mut self, mode: Mode) {
        if mode == Mode::Log {
            log::warn!(
                "RM allowlist in log mode: RM controls and classes it lacks are logged and \
                 forwarded to the host's RM anyway"
            );
        }
        self.mode = mode;
    }

    /// Hold the guest to the list of the release the host runs.
    pub fn set_driver(&mut self, v: DriverVersion) {
        let (release, exact) = rmallow::release_for(v);
        self.release = release;
        self.exact = exact;
        log::info!(
            "RM allowlist: host driver {v}, list of {}{} ({} of {} controls, {} of {} classes)",
            release.version(),
            if exact {
                ""
            } else {
                ", the nearest older release measured"
            },
            release.controls.len(),
            release.total_controls,
            release.classes.len(),
            release.total_classes
        );
    }

    /// Check an RM escape before it reaches the host: `escape` its number,
    /// `sent` the top-level block and the parameters after it as the guest
    /// sent them, `top` the top-level block's length. `Ok` lets it go.
    pub fn check(&mut self, escape: u32, sent: &[u8], top: usize) -> Result<(), Refusal> {
        let top_block = &sent[..top.min(sent.len())];
        let params = sent.get(top..).unwrap_or(&[]);
        let verdict = match escape {
            NV_ESC_RM_CONTROL => self.control(top_block, params),
            NV_ESC_RM_ALLOC => {
                // NVOS21 and NVOS64 have hClass at one place; the status
                // follows each.
                let at = if top == rmallow::NVOS64_SIZE {
                    rmallow::NVOS64_STATUS
                } else {
                    rmallow::NVOS21_STATUS
                };
                self.class(top_block, rmallow::NVOS64_H_CLASS, at)
            }
            NV_ESC_RM_ALLOC_MEMORY => {
                self.class(top_block, rmallow::NVOS02_H_CLASS, rmallow::NVOS02_STATUS)
            }
            NV_ESC_RM_ALLOC_OBJECT => {
                self.class(top_block, rmallow::NVOS05_H_CLASS, rmallow::NVOS05_STATUS)
            }
            NV_ESC_RM_ALLOC_CONTEXT_DMA2 => {
                self.class(top_block, rmallow::NVOS39_H_CLASS, rmallow::NVOS39_STATUS)
            }
            NV_ESC_RM_VID_HEAP_CONTROL => {
                let f = rd32(top_block, rmallow::NVOS32_FUNCTION)
                    .ok_or(Refusal::Errno(libc::EINVAL))?;
                if self.release.vidheap(f) {
                    Ok(())
                } else {
                    Err((
                        What::VidHeap(f),
                        Refusal::Status {
                            at: rmallow::NVOS32_STATUS,
                            status: NV_ERR_NOT_SUPPORTED,
                        },
                    ))
                }
            }
            _ => Ok(()),
        };
        let (what, refusal) = match verdict {
            Ok(()) => return Ok(()),
            Err(e) => e,
        };
        let name = match what {
            What::Control(cmd) => {
                self.refused_controls.add(cmd);
                format!(
                    "RM control {} ({cmd:#010x})",
                    rmallow::control_name(cmd).unwrap_or("unknown to every release measured")
                )
            }
            What::Class(class) => {
                self.refused_classes.add(class);
                format!(
                    "RM class {} ({class:#06x}) on escape {escape:#04x}",
                    rmallow::class_name(class).unwrap_or("unknown to every release measured")
                )
            }
            What::VidHeap(f) => format!("VID_HEAP_CONTROL function {f}"),
        };
        let why = match refusal {
            Refusal::Status { status, .. } if status == NV_ERR_INVALID_PARAM_STRUCT => {
                "sent with a parameter size RM does not take"
            }
            _ => "not in the allowlist",
        };
        match self.mode {
            Mode::Enforce => {
                log::warn!(
                    "{name} refused: {why} of host release {} (gen/rmallow_extract.py)",
                    self.release.version()
                );
                Err(refusal)
            }
            Mode::Log => {
                log::warn!(
                    "{name} would be refused ({why} of host release {}); forwarded, \
                     --rm-allowlist=log",
                    self.release.version()
                );
                Ok(())
            }
        }
    }

    fn control(&self, top: &[u8], params: &[u8]) -> Result<(), (What, Refusal)> {
        let short = |w| (w, Refusal::Errno(libc::EINVAL));
        let cmd = rd32(top, rmallow::NVOS54_CMD).ok_or_else(|| short(What::Control(0)))?;
        let size =
            rd32(top, rmallow::NVOS54_PARAMS_SIZE).ok_or_else(|| short(What::Control(cmd)))?;
        let status = rmallow::NVOS54_STATUS;
        if top.len() < status + 4 {
            return Err(short(What::Control(cmd)));
        }
        let unsupported = |c| {
            (
                What::Control(c),
                Refusal::Status {
                    at: status,
                    status: NV_ERR_NOT_SUPPORTED,
                },
            )
        };
        let Some(entry) = self.release.control(cmd) else {
            return Err(unsupported(cmd));
        };
        // RM takes exactly its own size (resControlLookup); zero is a
        // control with none. Only on the release measured.
        if let Some(want) = entry.size
            && self.exact
            && want != 0
            && size != want
        {
            return Err((
                What::Control(cmd),
                Refusal::Status {
                    at: status,
                    status: NV_ERR_INVALID_PARAM_STRUCT,
                },
            ));
        }
        // The control DEFERRED_API has RM run later, at the caller's
        // privilege, from the bundle it keeps: RM runs only its own few,
        // and each must be one the guest may call now.
        if DEFERRED_API.contains(&cmd) {
            let inner = rd32(params, DEFERRED_CMD).ok_or_else(|| short(What::Control(cmd)))?;
            if !self.release.deferred(inner) || self.release.control(inner).is_none() {
                return Err(unsupported(inner));
            }
        }
        Ok(())
    }

    fn class(&self, top: &[u8], class_at: usize, status: usize) -> Result<(), (What, Refusal)> {
        let class = rd32(top, class_at).ok_or((What::Class(0), Refusal::Errno(libc::EINVAL)))?;
        if top.len() < status + 4 {
            return Err((What::Class(class), Refusal::Errno(libc::EINVAL)));
        }
        if self.release.class(class) {
            Ok(())
        } else {
            Err((
                What::Class(class),
                Refusal::Status {
                    at: status,
                    status: NV_ERR_INVALID_CLASS,
                },
            ))
        }
    }

    /// The teardown report: what was refused (or, in log mode, would have
    /// been), by RM's names, so the list can grow from one run's log.
    pub fn report(&self) {
        let verb = match self.mode {
            Mode::Enforce => "refused",
            Mode::Log => "would have refused",
        };
        for line in self
            .refused_controls
            .lines(|c| format!("{}({c:#010x})", rmallow::control_name(c).unwrap_or("?")))
        {
            log::info!("RM allowlist {verb} control(s): {line}");
        }
        for line in self
            .refused_classes
            .lines(|c| format!("{}({c:#06x})", rmallow::class_name(c).unwrap_or("?")))
        {
            log::info!("RM allowlist {verb} class(es): {line}");
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn gate() -> RmAllow {
        let mut g = RmAllow::new(Mode::Enforce);
        g.set_driver(DriverVersion::new(610, 57, 4));
        g
    }

    fn nvos54(cmd: u32, params: &[u8]) -> Vec<u8> {
        let mut b = vec![0u8; 32];
        b[8..12].copy_from_slice(&cmd.to_le_bytes());
        b[24..28].copy_from_slice(&(params.len() as u32).to_le_bytes());
        b.extend_from_slice(params);
        b
    }

    fn with_class(len: usize, class: u32) -> Vec<u8> {
        let mut b = vec![0u8; len];
        b[12..16].copy_from_slice(&class.to_le_bytes());
        b
    }

    #[test]
    fn an_observed_control_passes_and_an_unknown_one_is_rms_not_supported() {
        let mut g = gate();
        // NV2080_CTRL_CMD_GPU_GET_INFO_V2, 580 bytes in 610.57.04.
        let ok = nvos54(0x2080_0102, &[0u8; 580]);
        assert_eq!(g.check(NV_ESC_RM_CONTROL, &ok, 32), Ok(()));
        for cmd in [0x2080_0112, 0x2080_0122, 0xdead_beef, 0x2080_a0ff] {
            let b = nvos54(cmd, &[0u8; 16]);
            assert_eq!(
                g.check(NV_ESC_RM_CONTROL, &b, 32),
                Err(Refusal::Status {
                    at: 28,
                    status: NV_ERR_NOT_SUPPORTED
                }),
                "{cmd:#x}"
            );
        }
    }

    #[test]
    fn a_parameter_size_rm_does_not_take_is_refused_on_the_release_measured() {
        let mut g = gate();
        let b = nvos54(0x2080_0102, &[0u8; 64]);
        assert_eq!(
            g.check(NV_ESC_RM_CONTROL, &b, 32),
            Err(Refusal::Status {
                at: 28,
                status: NV_ERR_INVALID_PARAM_STRUCT
            })
        );
        // Between releases the size is RM's to check, not the table's.
        let mut between = RmAllow::new(Mode::Enforce);
        between.set_driver(DriverVersion::new(600, 1, 0));
        assert_eq!(between.check(NV_ESC_RM_CONTROL, &b, 32), Ok(()));
    }

    #[test]
    fn a_deferred_api_bundle_is_held_to_the_same_list() {
        let mut g = RmAllow::new(Mode::Enforce);
        g.set_driver(DriverVersion::new(610, 57, 4));
        // The class that runs deferred calls is not allocatable, so its
        // control is refused whatever it bundles.
        let mut p = vec![0u8; 64];
        p[4..8].copy_from_slice(&0x2080_012bu32.to_le_bytes());
        assert!(
            g.check(NV_ESC_RM_CONTROL, &nvos54(0x5080_0101, &p), 32)
                .is_err()
        );
    }

    #[test]
    fn classes_are_checked_on_every_escape_that_allocates_one() {
        let mut g = gate();
        for (escape, len, status) in [
            (NV_ESC_RM_ALLOC, 48, 40),
            (NV_ESC_RM_ALLOC, 32, 28),
            (NV_ESC_RM_ALLOC_MEMORY, 56, 40),
            (NV_ESC_RM_ALLOC_OBJECT, 20, 16),
            (NV_ESC_RM_ALLOC_CONTEXT_DMA2, 56, 48),
        ] {
            // NV01_MEMORY_SYSTEM, observed; NV40_I2C, never.
            assert_eq!(g.check(escape, &with_class(len, 0x3e), len), Ok(()));
            assert_eq!(
                g.check(escape, &with_class(len, 0x402c), len),
                Err(Refusal::Status {
                    at: status,
                    status: NV_ERR_INVALID_CLASS
                }),
                "escape {escape:#x}"
            );
        }
        assert_eq!(
            g.check(NV_ESC_RM_ALLOC, &[0u8; 8], 8),
            Err(Refusal::Errno(libc::EINVAL))
        );
    }

    #[test]
    fn vid_heap_functions_are_held_to_the_classes_they_allocate() {
        let mut g = gate();
        let heap = |f: u32| {
            let mut b = vec![0u8; 184];
            b[8..12].copy_from_slice(&f.to_le_bytes());
            b
        };
        assert_eq!(g.check(NV_ESC_RM_VID_HEAP_CONTROL, &heap(2), 184), Ok(()));
        assert_eq!(g.check(NV_ESC_RM_VID_HEAP_CONTROL, &heap(3), 184), Ok(()));
        assert_eq!(
            g.check(NV_ESC_RM_VID_HEAP_CONTROL, &heap(99), 184),
            Err(Refusal::Status {
                at: 20,
                status: NV_ERR_NOT_SUPPORTED
            })
        );
    }

    #[test]
    fn log_mode_forwards_what_it_would_refuse_and_counts_it() {
        let mut g = gate();
        g.set_mode(Mode::Log);
        let b = nvos54(0xdead_beef, &[]);
        assert_eq!(g.check(NV_ESC_RM_CONTROL, &b, 32), Ok(()));
        assert_eq!(g.refused_controls.get(0xdead_beef), Some(1));
        assert_eq!("log".parse::<Mode>(), Ok(Mode::Log));
        assert_eq!("enforce".parse::<Mode>(), Ok(Mode::Enforce));
        assert!("off".parse::<Mode>().is_err());
    }

    #[test]
    fn other_escapes_are_not_this_gates() {
        let mut g = gate();
        assert_eq!(g.check(NV_ESC_RM_FREE, &[0u8; 16], 16), Ok(()));
        assert_eq!(g.check(NV_ESC_RM_MAP_MEMORY, &[0u8; 56], 56), Ok(()));
    }
}
