//! Compile the module's C parsers -- nvgpu_i2.c, nvgpu_rmio.c and the tables
//! in nvgpu_schema.c, as they are -- against the userspace shim (`shim/`,
//! and an `nvgpu.h` made here from the real one's IOCTL2 section) and the
//! harness (`c/harness.c`) that forwards what they call to the test's world.

use std::env;
use std::fs;
use std::path::PathBuf;

const PREAMBLE: &str = r#"/* SPDX-License-Identifier: GPL-2.0-only */
/* Generated by driver/rust/difftest/build.rs: the module's nvgpu.h, cut down
 * to what the parsers use, and its IOCTL2 section verbatim. */
#ifndef NVGPU_H
#define NVGPU_H

#include <linux/ioctl.h>
#include <linux/kernel.h>
#include <linux/time.h>
#include <linux/types.h>

#include "nvgpu_wire.h"

struct nvgpu_schema_set;
struct nvgpu_uvm_table;
struct page;

struct virtio_device {
  int dev;
};

struct nvgpu_device {
  struct virtio_device *vdev;
  char driver_version[32];
  struct nvgpu_fd_translation_entry fd_translations[16];
  u32 num_fd_translations;
  bool v2;
  u32 backend_caps;
  u32 max_req;
  u32 max_resp;
  const struct nvgpu_schema_set *schema;
  const struct nvgpu_uvm_table *uvm;
};

struct nvgpu_fd {
  struct nvgpu_device *dev;
  u32 handle;
};

long nvgpu_ioctl_fd(struct nvgpu_fd *nfd, unsigned int cmd, unsigned long arg);
long nvgpu_uvm_ioctl_fd(struct nvgpu_fd *nfd, unsigned int cmd,
                        unsigned long arg);
long nvgpu_ioctl_modeset(struct nvgpu_fd *nfd, unsigned int cmd,
                         void __user *uarg);
int nvgpu_handle_for_fd(struct nvgpu_device *dev, int guest_fd, u32 *handle);
bool nvgpu_proc_ids(const struct nvgpu_device *dev);
bool nvgpu_proc_euid(const struct nvgpu_device *dev);
void nvgpu_proc_id_fill(const struct nvgpu_device *dev, void *dst);
bool nvgpu_host_clock_to_guest(struct nvgpu_device *dev, clockid_t clk,
                               s64 host_ns, s64 *guest_ns);

bool nvgpu_osdesc_ioctl(struct nvgpu_fd *nfd, unsigned int cmd,
                        void __user *uarg, const void *outer, unsigned int sz,
                        long *ret);
bool nvgpu_osdesc_candidate(unsigned int nr, unsigned int sz);
void nvgpu_osdesc_reap(struct nvgpu_device *dev);
bool nvgpu_osdesc_ok(const struct nvgpu_device *dev);
int nvgpu_osdesc_pin(unsigned long start, unsigned long npages, bool write,
                     struct page **pages);
void nvgpu_osdesc_keep(struct nvgpu_device *dev, u64 id, struct page **pages,
                       unsigned long npages, bool write);
void nvgpu_osdesc_unpin(struct page **pages, unsigned long n, bool write);
int nvgpu_osdesc_send(struct nvgpu_device *dev, void *req, int req_len,
                      void *resp, int resp_len, u32 *used,
                      struct page **pages, unsigned long npages, bool write);

struct nvgpu_tbuf;
struct nvgpu_tbuf *nvgpu_tbuf_alloc(size_t len, gfp_t gfp);
void nvgpu_tbuf_free(struct nvgpu_tbuf *tb);
void nvgpu_tbuf_on_free(struct nvgpu_tbuf *tb, void (*fn)(void *arg),
                        void *arg);
size_t nvgpu_tbuf_len(const struct nvgpu_tbuf *tb);
int nvgpu_tbuf_write(struct nvgpu_tbuf *tb, size_t off, const void *src,
                     size_t len);
int nvgpu_tbuf_read(const struct nvgpu_tbuf *tb, size_t off, void *dst,
                    size_t len);
#define NVGPU_XF_EXECUTOR (1u << 0)
int nvgpu_xfer(struct nvgpu_device *dev, struct nvgpu_tbuf *req,
               struct nvgpu_tbuf *resp, u32 flags, u32 *used_len);
int nvgpu_send_recv_used(struct nvgpu_device *dev, void *req, int req_len,
                         void *resp, int resp_len, u32 *used_len);
static inline bool nvgpu_resp_has(u32 used, size_t off, size_t len) {
  return off <= used && len <= used - off;
}
void nvgpu_close_handle_async(struct nvgpu_device *dev, u32 handle);
void nvgpu_gem_close_async(struct nvgpu_device *dev, u32 file_handle,
                           u32 gem);

"#;

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let driver = manifest.join("../..").canonicalize().expect("driver/");
    let out = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR")).join("c");
    fs::create_dir_all(&out).expect("OUT_DIR/c");

    let real = fs::read_to_string(driver.join("nvgpu.h")).expect("driver/nvgpu.h");
    let start = real
        .find("/* ── IOCTL2 interpreter")
        .expect("nvgpu.h's IOCTL2 section");
    fs::write(out.join("nvgpu.h"), format!("{PREAMBLE}{}", &real[start..])).expect("nvgpu.h");

    // The sources are copied next to the generated nvgpu.h, so that their
    // `#include "nvgpu.h"` finds it before the real one.
    let mut files = Vec::new();
    for f in [
        "nvgpu_i2.c",
        "nvgpu_rmio.c",
        "nvgpu_schema.c",
        "nvgpu_atomic.c",
    ] {
        fs::copy(driver.join(f), out.join(f)).expect(f);
        files.push(out.join(f));
        println!("cargo:rerun-if-changed={}", driver.join(f).display());
    }
    fs::copy(manifest.join("c/harness.c"), out.join("harness.c")).expect("harness.c");
    files.push(out.join("harness.c"));
    for d in [
        "nvgpu.h",
        "nvgpu_wire.h",
        "nvgpu_rm_intercepts.h",
        "gen",
        "../driver/rust/difftest/c",
        "../driver/rust/difftest/shim",
    ] {
        println!("cargo:rerun-if-changed={}", driver.join(d).display());
    }

    cc::Build::new()
        .files(&files)
        .include(manifest.join("shim"))
        .include(&out)
        .include(&driver)
        .std("gnu11")
        // The kernel builds with -Wall, not -Wextra.
        .extra_warnings(false)
        .flag("-Wall")
        .flag("-Wno-unused-function")
        // The kernel's own flags: no strict aliasing, char is unsigned.
        .flag("-fno-strict-aliasing")
        .flag("-funsigned-char")
        // Undefined behaviour in the C traps rather than goes on quietly.
        .flag("-fsanitize=undefined")
        .flag("-fsanitize-undefined-trap-on-error")
        .warnings_into_errors(true)
        .compile("nvgpu_c");
}
