#!/usr/bin/env bash
# Build the offscreen draw probe. Run this on the HOST: the guest image has no
# compiler and no Vulkan headers, and the host is the same userspace, so the
# binary is staged into the image the way the module is.
#
#   ./build-offscreen.sh [output-path]
#
# Needs: gcc, glslc (shaderc) or glslangValidator, and Vulkan headers.
# On Arch: pacman -S vulkan-headers shaderc
# On Ubuntu: apt install libvulkan-dev glslc
# Without root, point VULKAN_INCLUDE at any tree holding vulkan/vulkan.h.
#
# The probe links libvulkan.so.1 dynamically -- the guest image already carries
# the loader (it runs vulkaninfo). The NVIDIA ICD itself comes from the host's
# staged tree over virtio-fs at run time, never from the image.
set -euo pipefail

HERE=$(cd "$(dirname "$0")" && pwd)
OUT=${1:-$HERE/offscreen-draw}
TMP=$(mktemp -d); trap 'rm -rf "$TMP"' EXIT

if command -v glslc >/dev/null; then
    compile() { glslc -o "$2" "$1"; }
elif command -v glslangValidator >/dev/null; then
    compile() { glslangValidator -V -o "$2" "$1"; }
else
    echo "need glslc or glslangValidator" >&2; exit 1
fi

# SPIR-V goes in as a C array so the probe is one self-contained file in the
# guest -- no shader blobs to stage and keep in step with the binary.
for s in vert frag; do
    compile "$HERE/offscreen.$s" "$TMP/$s.spv"
    { echo "// generated by build-offscreen.sh -- do not edit"
      echo "static const unsigned char offscreen_${s}_spv[] = {"
      od -An -tx1 -v < "$TMP/$s.spv" | sed 's/ \([0-9a-f][0-9a-f]\)/0x\1,/g'
      echo "};"
    } > "$TMP/offscreen_$s.h"
done

gcc -O2 -Wall -Wextra -I"$TMP" ${VULKAN_INCLUDE:+-I"$VULKAN_INCLUDE"} \
    -o "$OUT" "$HERE/offscreen-draw.c" -lvulkan
echo "built: $OUT"
